addSbtPlugin("org.scalameta"             % "sbt-scalafmt"               % "2.4.6")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"               % "0.1.20")
addSbtPlugin("com.github.sbt"            % "sbt-ci-release"             % "1.5.12")
addSbtPlugin("io.chrisdavenport"         % "sbt-mima-version-check"     % "0.1.2")
addSbtPlugin("io.chrisdavenport"         % "sbt-no-publish"             % "0.1.0")
addSbtPlugin("org.scalameta"             % "sbt-mdoc"                   % "2.3.7")
addSbtPlugin("com.typesafe.sbt"          % "sbt-site"                   % "1.4.1")
addSbtPlugin("com.eed3si9n"              % "sbt-unidoc"                 % "0.4.3")
addSbtPlugin("io.github.jonas"           % "sbt-paradox-material-theme" % "0.6.0")
addSbtPlugin("org.jmotor.sbt"            % "sbt-dependency-updates"     % "1.2.9")

ThisBuild / libraryDependencySchemes ++= Seq("org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always)
